### ISSUE TITLE
Not able to pull any images from remote source using helm installer

### ISSUE THREAD

**Issue by ghost** [jetstack/terraform-google-gke-cluster#25]
Using helm to deploy several tools. 6 nodes in the cluster with plenty of resources. Not able to pull any images. Am I missing some kind of security feature?

```
NAMESPACE        NAME                                                            READY   STATUS              RESTARTS   AGE
cert-manager     cert-manager-6f68b58796-pq5n7                                   0/1     ImagePullBackOff    0          56s
cert-manager     cert-manager-cainjector-67b4696847-69d8p                        0/1     ImagePullBackOff    0          56s
cert-manager     cert-manager-webhook-6f58884b96-zvxb5                           0/1     ContainerCreating   0          56s
default          kube-state-metrics-8d44f5779-h4krz                              0/1     ImagePullBackOff    0          47s
default          metricbeat-574f7df9d4-8d9tl                                     0/1     ImagePullBackOff    0          51s
default          metricbeat-64n7n                                                0/1     ImagePullBackOff    0          51s
default          metricbeat-kpg8c                                                0/1     ImagePullBackOff    0          51s
default          metricbeat-nnnrn                                                0/1     ImagePullBackOff    0          51s
default          metricbeat-nxhl6                                                0/1     ImagePullBackOff    0          51s
default          metricbeat-sdxcl                                                0/1     ImagePullBackOff    0          51s
default          metricbeat-zh2w8                                                0/1     ImagePullBackOff    0          51s
infrastructure   ni-traefik-5677796f6f-x2ftb                                     0/1     ImagePullBackOff    0          6m12s
infrastructure   ni-traefik-8655c466b5-v2pbl                                     0/1     ImagePullBackOff    0          6m9s
```

**Comment by ghost** [comment]
Changed to public nodes and I was able to pull images.

**Comment by znat** [comment]
The proper way to solve that seems to be using a mirror of the Docker Hub in gcr.

See the last section of [this page](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters):Can't pull image from public Docker Hub

Referencing this link: https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring
Not sure how changing the Docker daemon config can be done in terraform though

**Comment by wwwil** [comment]
Yeah, as the module is going for best practises on security you won't be able to pull images from outside your GCR, but can mirror images as required. This means you can enforce vulnerability scanning and get more visibility on what images are in use.

Most Helm charts allow you to change the image registry in their `values.yaml` too so you can point that to you private mirror.

Alternatively you can use Cloud NAT to allow the private nodes to access the internet. https://medium.com/google-cloud/using-cloud-nat-with-gke-cluster-c82364546d9e

I'm planning to add this to the README and look at adding Cloud NAT setup to the example project too as it's not made clear how it should be handled currently.

**Comment by znat** [comment]
Thanks for the Cloud NAT tip! I'm the end I had disabled private nodes, also because apps running on the cluster need access to the internet, now it looks we can have best of both worlds

**Comment by thiagolsfortunato** [comment]
@wwwil thanks a lot! :heart:
