### ISSUE TITLE
Recommended way to add configuration blocks to cluster

### ISSUE THREAD

**Issue by znat** [jetstack/terraform-google-gke-cluster#33]
I'm relatively new to Terraform, sorry in advance if the question is newbiish... 
I would like to add an `istio_config` block to the cluster. It currently requires the `google-beta` provider, but if we leave that aside, is there a way to extend the cluster configuration from the module section in the parent project without modifying the generated/imported module?
Thanks

**Comment by wwwil** [comment]
Hi! No worries 😄 I don't think there is a way to add blocks to modules, but I will look into it.

I would like to add an `istio_config` so am open to any PRs, though will also need to look into the `google-beta` provider and what effect switching to that will have. There are a few other features I'd like to add that also need it so would be good to have!
