### ISSUE TITLE
Add instructions/best practices for cert-manager installation

### ISSUE THREAD

**Issue by znat** [jetstack/terraform-google-gke-cluster#37]
Installing the latest cert manager via terraform is not trivial as it requires 1) configuring helm provider with jetstack repo, and 2) apply the CRD manifest.

Something like this might work but since cert-manager is a Jetstack product an official recommendation would be nice.

```
resource "kubernetes_namespace" "cert-manager" {
  metadata {
    labels {
      "certmanager.k8s.io/disable-validation" = "true"
    }
    name = "cert-manager"
  }
}
data "helm_repository" "jetstack" {
    name = "jetstack"
    url  = "https://charts.jetstack.io"
}

resource "null_resource" "cert-manager" {
  provisioner "local-exec" {
     when "create"
    command = "kubectl apply -f ${local.certManagerManifest}"
  }

  provisioner "local-exec" {
    when = "destroy"
    command = "kubectl delete -f ${local.certManagerManifest}"
  }

resource "helm_release" "cert-manager" {
    name      = "cert-manager"
    namespace = "cert-manager"
    chart     = "jetstack/cert-manager"
    version   = "v0.8.1"
}
}
```

Note: the code above doesn't work completely, still something to figure out to avoid the webhook permission error.

**Comment by wwwil** [comment]
I think the Jetstack recommendation would be to not use Terraform for cluster resources. While it works very well for infrastructure it can create unnecessary work when managing things inside the cluster, so it's better to switch to another tool like Helm or Kustomize at this level.

If you're looking for a single way to wrap everything up to deploy a full stack then using a bash script or Makefile would be the recommendation.

**Comment by wwwil** [comment]
I've also been advised that Terraform can't handle Custom Resource Definitions (CRDs) which are required by cert-manager to represent Certificates, Issuers, etc. so I think it may impossible to install with Terraform.

**Comment by MPV** [comment]
I can recommend the `terraform-provider-k8s` provider, which can install custom manifests. 

I do this for cert-manager like this:

```hcl
variable "cert_manager_version" {
  default     = "0.11"
}

data "http" "cert-manager-crd" {
  url = "https://raw.githubusercontent.com/jetstack/cert-manager/release-${var.cert_manager_version}/deploy/manifests/00-crds.yaml"
}

resource "k8s_manifest" "cert-manager-crd" {
  content = data.http.cert-manager-crd.body
}
```

See https://github.com/banzaicloud/terraform-provider-k8s
