### ISSUE TITLE
Unable to create vpc-subnetwork

### ISSUE THREAD

**Issue by alljames** [jetstack/terraform-google-gke-cluster#52]
Encountering an error on `terraform apply`. Strangely, only seven resources are marked for creation created in `terraform plan`, none of which is a vpc network or subnetwork.

```
Error : Error applying plan:

1 error occurred:
	* google_container_cluster.cluster: 1 error occurred:
	* google_container_cluster.cluster: googleapi: Error 400: Subnetwork "projects/<GCP_PROJECT>/regions/europe-west1/subnetworks/vpc-subnetwork" is not valid for Network "vpc-network"., badRequest
```

```
$ terraform version
Terraform v0.11.14
+ provider.google v2.5.1
+ provider.random v2.1.1
```

**Comment by wwwil** [comment]
I've not been able to reproduce this issue and it uses an older version of Terraform so I'm going to close. Feel free to reopen if you encounter this problem again. Thanks!
